version: '3'
services:
  kafka:
    container_name: kafka
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx1G"
    volumes:
      - ./kafka_data:/var/lib/kafka/data
      - ./kafka_logs:/var/lib/kafka/logs
