spring:
  config:
    activate:
      on-profile: dev
  application:
    name: brainpix
  datasource:
    url: ENC(TUndP/xaOEDBpOvFTYrYrf2wxeXzBWxYD4axrevm8gozV85pc6I1UJq+sZk/4AFmclNAAq+B16ZGAzTXHJE+nvqLwaReXqZdpQ9jpt3YxL5FFXIow2Mj+CIEJWfbebMznxvmxmfi7Sr4U7FZRc53N7cL4GpXw9Y6yCHRqPtS7/U=)
    username: ENC(1FyUCTH5uqA1rVjkWkAbQLaNZCmBQLb44EZSuQYOonvV44lFv+vGbFHXqYf83jw2)
    password: ENC(qMqB9te807UWNY97Qi2F5FKRK+E6uceslH7DU5aCz2HmY45o4FZBH71Ell6zolarVnzGSSuFVWB0es3o2pCBzhOkGH+1Li22DmXxyGtzbZw=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: ENC(ntZhfbWKkCOZNqOpRHvqXNo6dobNfFZ/Di5ttdUS2DYYcrgyKJ65WS2QwDANfHxaLz5oYrPgYOiEfRgtWSCq+Iz9sMKPumkayGCZRCGK+zrV4SjF0DHUHMgCWOjgiZJKJBbHxKbwdgwHHnNAJkYGixZMTy2fTp+5OJKFOMSn5Lb5Mz+UXFnMKfrIhnIV6HAjd8Lew8yry6npsHneBiXzlA==)
  mail:
    host: ENC(5WpWHIIQtBVAYDvxlhS3jjaEZXLMSQjIqO5kXPrLze/PM29RbHV3U8Z6ihG501qp)
    username: ENC(prCp5Ol/nxisuAB+sy7D1brjRQDnk1sArHFMZ1J310Q7O/DOed09i9OXAiZBSrh2Lae9pI7soUI6dxdpgcx3KA==)
    password: ENC(15oeubKhgXAzVQFYZJlBH+zhMn9nO9baDacvG0xfZVKCALibswPooowYZbQHja6X/kgi0gSJ5/kVx6yuQhgz+Q==)
jasypt:
  encryptor:
    password: jasyptKey
    bean: jasyptEncryptor

jwt:
  secret: ENC(IM7p+pHVt55x2ugo5fWNu03bDw76hiCwRRWk/Os7r3Cvpcbk1lKtLccdbaWmCI+bOTsjepwpIpbHSVorbDTd0t0JfKMuskq75YfF9ehPzjw/4nEkK5Pli/FnDqeiT6fiFSnVvlGrsswp3BVR0YOzwbxMTAz06cGEu+fNqW3DzLBpv3WGIzcMP4BodGohaoct)

springdoc:
  use-fqn: true

kakao:
  pay:
    secret-key: ENC(97EXNTaZOAO5M/YmiG831cRnVLAaz2aVg3+bWr6obBiBk5k0sg91JTZv1sGHFhCNTatNJV4XX43l5Qxz1eBk0m1QMJ/VDLJ9T6AC/6yuISQ=)
    cid: ENC(+Kb6JKxydvdU8AtNjy6i8E/0cr3mcK3/yIXO4oULT/Z41Ri57uepQtt7vEAl1uyk)
    ready-url: https://open-api.kakaopay.com/online/v1/payment/ready
    approve-url: https://open-api.kakaopay.com/online/v1/payment/approve

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ENC(BmfwEKh+yJlv4gszhV+HyfOeEWIu8ZVQp86f2Oug/8y1yCo9p9elIJvoB6t9cmQF4R6DhMOcZAY5o0L5fj5Zig==)
      secret-key: ENC(KfOW6KGilnbGL7EE4H8gC6KtfPINKq5pV73jDiVW/YKZN5cZd/hQvy62FUS/VIbEvQ/fkcGeUzrwhkY9zrMKnq+j/l6Anw1b5TsHYLj8+EA=)
    s3:
      bucket: ENC(rrnE1x4Zt298sljRL6ZRmr/hLjBr00/DV0MVRinK6bnb3PGWraGDEFVkwQ6C/2qI)
    stack:
      auto: false
