package com.brainpix.alarm.template;

public enum AlarmType {
	QNA_COMMENT,
	QNA_COMMENT_REPLY,

	IDEA_SOLD,

	REQUEST_TASK_APPLY,
	REQUEST_TASK_APPROVE,

	COLLABORATION_TASK_APPLY,
	COLLABORATION_TASK_APPROVE,
	COLLABORATION_TASK_REJECT
}
