name: CI Pipeline

on:
  pull_request:
    # pull request의 대상 브랜치를 develop으로 제한
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
      # PR 브랜치 체크아웃
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Java 환경설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # Gradle 권한부여
      - name: Grant execute permission fom gradlew
        run: chmod +x gradlew

      # 현재 브랜치 기준 빌드 테스트
      - name: Build jar
        run: ./gradlew compileJava -x test

      # develop 브랜치와의 병합 시뮬레이션
      - name: Test mergeability with develop branch
        run: |
          git fetch origin develop
          git merge origin/develop --no-commit --no-ff || { echo "현재 브랜치는 develop 브랜치와 병합시 conflict가 발생합니다."; exit 1; }

      # 병합 시뮬레이션 후 빌드 테스트
      - name: Build jar
        run: ./gradlew compileJava -x test
